language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=pypy
  - TOXENV=py26-colorama
  - TOXENV=py27-colorama
  - TOXENV=py32-colorama
  - TOXENV=py33-colorama
  - TOXENV=pypy-colorama
  - TOXENV=lint
install:
  - pip install tox
script:
  - tox
matrix:
  allow_failures:
    - env: TOXENV=lint
sudo: false
